spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contaskdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    validate-on-migrate: true
    default-schema: public
    